// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVYhWaz1fx_NcppeAE8GQWlzeebr676r0',
    appId: '1:300466326598:web:027c12c4d9b6bb66a50e47',
    messagingSenderId: '300466326598',
    projectId: 'basic-registration-firebase',
    authDomain: 'basic-registration-firebase.firebaseapp.com',
    storageBucket: 'basic-registration-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwq_bY-QZ_1orHDfRlvS1wMaowiyXNaZg',
    appId: '1:300466326598:android:95545a38354fd896a50e47',
    messagingSenderId: '300466326598',
    projectId: 'basic-registration-firebase',
    storageBucket: 'basic-registration-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-bQSjv2DhjmT5FFB0qUry0JzfuVgmOfE',
    appId: '1:300466326598:ios:eb801ecd470fd9ada50e47',
    messagingSenderId: '300466326598',
    projectId: 'basic-registration-firebase',
    storageBucket: 'basic-registration-firebase.appspot.com',
    iosBundleId: 'com.example.basicRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-bQSjv2DhjmT5FFB0qUry0JzfuVgmOfE',
    appId: '1:300466326598:ios:e69874f486c3a581a50e47',
    messagingSenderId: '300466326598',
    projectId: 'basic-registration-firebase',
    storageBucket: 'basic-registration-firebase.appspot.com',
    iosBundleId: 'com.example.basicRegistration.RunnerTests',
  );
}
